"""
Empire GTM Layer — ICP scoring, signal detection, campaign generation, sequence creation, weekly updates.
Connects to Revenue OS to provide GTM intelligence for every generated revenue system.
"""

import json
import os
import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

DATA_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data", "gtm")


def _load(name: str) -> dict:
    path = os.path.join(DATA_DIR, f"{name}.json")
    if not os.path.exists(path):
        return {}
    with open(path) as f:
        return json.load(f)


def _save(name: str, data: dict):
    os.makedirs(DATA_DIR, exist_ok=True)
    path = os.path.join(DATA_DIR, f"{name}.json")
    with open(path, "w") as f:
        json.dump(data, f, indent=2)


def _load_list(name: str) -> list:
    d = _load(name)
    if isinstance(d, list):
        return d
    return d.get("campaigns", []) if name == "campaigns" else d.get("scoring_outputs", []) if name == "scoring_outputs" else d.get("updates", []) if name == "weekly_updates" else []


def _save_list(name: str, items: list):
    if name == "campaigns":
        _save(name, {"description": "GTM campaigns generated by Empire Revenue OS.", "campaigns": items})
    elif name == "scoring_outputs":
        _save(name, {"description": "Buyer scoring outputs from Empire GTM Layer.", "scoring_outputs": items})
    elif name == "weekly_updates":
        _save(name, {"description": "Weekly GTM updates generated by Empire GTM Layer.", "updates": items})


# ---------------------------------------------------------
# LOADERS
# ---------------------------------------------------------

def load_gtm_context() -> dict:
    return {
        "profile": _load("profile"),
        "icp": _load("icp_definition"),
        "signals": _load("signal_library"),
        "positioning": _load("positioning"),
        "competitors": _load("competitor_radar"),
        "personas": _load("personas"),
        "campaigns": _load_list("campaigns"),
        "scoring_outputs": _load_list("scoring_outputs"),
        "weekly_updates": _load_list("weekly_updates"),
    }


def save_gtm_context(context: dict):
    for key in ("profile", "icp", "signals", "positioning", "competitors", "personas"):
        if key in context:
            _save(key, context[key])
    if "campaigns" in context:
        _save_list("campaigns", context["campaigns"])
    if "scoring_outputs" in context:
        _save_list("scoring_outputs", context["scoring_outputs"])
    if "weekly_updates" in context:
        _save_list("weekly_updates", context["weekly_updates"])


# ---------------------------------------------------------
# SCORING
# ---------------------------------------------------------

def score_buyer_profile(profile: dict, context: dict) -> dict:
    icp = context.get("icp", {})
    segments = icp.get("icp_segments", [])
    signals = context.get("signals", {}).get("signals", [])

    segment = profile.get("segment", "")
    persona_type = profile.get("persona_type", "")
    priority_score = profile.get("priority_score", 50)

    icp_fit = 0
    matched_segment = None
    for seg in segments:
        if seg["segment"].lower() in segment.lower() or seg["segment"].lower() in persona_type.lower():
            icp_fit = seg.get("fit_score", 50)
            matched_segment = seg
            break
    if not icp_fit and segment:
        for seg in segments:
            if any(s.lower() in segment.lower() for s in seg.get("signals", [])):
                icp_fit = seg.get("fit_score", 30) - 10
                matched_segment = seg
                break
    if not icp_fit:
        icp_fit = 30

    signal_score = 0
    detected_signals = []
    for sig in signals:
        sig_personas = [p.lower() for p in sig.get("persona_types", [])]
        if persona_type.lower() in sig_personas or segment.lower() in sig_personas:
            detected_signals.append({
                "signal_id": sig.get("id"),
                "signal_name": sig.get("name"),
                "priority": sig.get("priority"),
                "sequence_type": sig.get("sequence_type"),
                "outreach_angle": sig.get("outreach_angle"),
            })
            signal_score = max(signal_score, sig.get("priority", 0))

    if not detected_signals:
        signal_score = max(0, priority_score - 20)

    total_score = min(100, icp_fit + signal_score)

    tier = _assign_tier(total_score)

    return {
        "persona_type": persona_type,
        "segment": segment,
        "icp_fit": icp_fit,
        "signal_score": signal_score,
        "total_score": total_score,
        "tier": tier,
        "detected_signals": detected_signals[:3],
        "best_channel": profile.get("best_channel", matched_segment.get("best_channels", ["email"])[0] if matched_segment else "email"),
        "recommended_action": _action_for_tier(tier, profile),
        "recommended_sequence_type": detected_signals[0]["sequence_type"] if detected_signals else "automated_nurture" if tier in ("Tier 3", "Monitor") else "personalized",
    }


def score_account(account: dict, context: dict) -> dict:
    icp = context.get("icp", {})
    segments = icp.get("icp_segments", [])
    signals_lib = context.get("signals", {}).get("signals", [])

    name = account.get("name", "Unknown")
    segment = account.get("segment", "")
    signals_raw = account.get("signals", [])

    icp_fit = 0
    for seg in segments:
        if seg["segment"].lower() in segment.lower():
            icp_fit = seg.get("fit_score", 50)
            break
    if not icp_fit:
        icp_fit = 30

    urgency = account.get("urgency", "normal")
    urgency_map = {"critical": 20, "high": 15, "normal": 10, "low": 5}
    urgency_score = urgency_map.get(urgency, 10)

    budget = account.get("budget", 0)
    budget_score = min(15, budget / 100) if budget else 0

    signal_score = 0
    detected = []
    for s in signals_raw:
        for lib_sig in signals_lib:
            if lib_sig.get("name", "").lower() in s.lower():
                detected.append(lib_sig)
                signal_score = max(signal_score, lib_sig.get("priority", 0))
    if not detected and signals_raw:
        signal_score = 20

    total_score = min(100, icp_fit + urgency_score + budget_score + signal_score)
    tier = _assign_tier(total_score)

    return {
        "name": name,
        "segment": segment,
        "icp_fit": icp_fit,
        "urgency_score": urgency_score,
        "budget_score": budget_score,
        "signal_score": signal_score,
        "total_score": total_score,
        "tier": tier,
        "detected_signals": [{"signal_id": s.get("id"), "signal_name": s.get("name")} for s in detected[:3]],
        "recommended_action": _action_for_tier(tier, account),
    }


def _assign_tier(score: int) -> str:
    if score >= 80:
        return "Tier 1"
    if score >= 60:
        return "Tier 2"
    if score >= 40:
        return "Tier 3"
    if score >= 20:
        return "Monitor"
    return "Exclude"


def _action_for_tier(tier: str, profile: dict) -> str:
    actions = {
        "Tier 1": "Immediate personalized outreach within 24 hours",
        "Tier 2": "Signal-triggered sequence within 48 hours",
        "Tier 3": "Automated nurture sequence",
        "Monitor": "Track and re-score weekly",
        "Exclude": "No outreach — does not fit ICP",
    }
    return actions.get(tier, "No action")


# ---------------------------------------------------------
# SIGNAL DETECTION
# ---------------------------------------------------------

def detect_signals(input_data: dict, context: dict) -> dict:
    signals_lib = context.get("signals", {}).get("signals", [])
    business_name = input_data.get("business_name", "")
    business_type = input_data.get("business_type", "other")
    offer = input_data.get("current_offer", "")
    target = input_data.get("target_customer", "")
    constraints = input_data.get("constraints", "")
    notes = input_data.get("links_or_notes", "")
    channel = input_data.get("preferred_sales_channel", "mixed")

    combined = f"{business_name} {offer} {target} {constraints} {notes}".lower()

    matched_signals = []
    for sig in signals_lib:
        persona_types = [p.lower() for p in sig.get("persona_types", [])]
        if business_type.lower() in " ".join(persona_types):
            matched_signals.append(sig)
            continue
        if target.lower() in " ".join(persona_types):
            matched_signals.append(sig)
            continue
        keywords = sig.get("name", "").lower().split()
        if any(k in combined for k in keywords):
            matched_signals.append(sig)

    matched_signals = matched_signals[:5]

    return {
        "business_name": business_name,
        "detected_signals": [
            {
                "signal_id": s.get("id"),
                "signal_name": s.get("name"),
                "priority": s.get("priority"),
                "sequence_type": s.get("sequence_type"),
                "outreach_angle": s.get("outreach_angle", ""),
            }
            for s in matched_signals
        ],
        "signal_count": len(matched_signals),
        "best_channel": channel,
        "summary": f"Detected {len(matched_signals)} signal(s) for {business_name}" if matched_signals else f"No strong signals detected for {business_name}",
    }


# ---------------------------------------------------------
# SIGNAL → SEQUENCE
# ---------------------------------------------------------

def build_signal_to_sequence(signal: dict, persona: dict, offer: dict, context: dict) -> dict:
    signal_name = signal.get("signal_name", "General signal")
    persona_type = persona.get("type", "general")
    offer_name = offer.get("name", "Revenue System")
    channel = persona.get("best_channel", "email")

    sequence_type = signal.get("sequence_type", "automated_nurture")

    sequences = {
        "personalized": [
            {"day": 1, "action": f"Send personalized DM via {channel}", "template": f"Hey {{name}}, I noticed {{signal_angle}}. We generated a revenue system for {offer_name} — want to see it?", "channel": channel},
            {"day": 3, "action": "Follow up with value add", "template": f"Hey {{name}}, following up on the {offer_name} system. Quick wins: {{quick_win}}. Worth 5 min?", "channel": channel},
            {"day": 7, "action": "Call or close attempt", "template": f"Last follow-up on the {offer_name} system. If timing is off, no worries — the offer is ready when you are.", "channel": channel},
        ],
        "signal_triggered": [
            {"day": 1, "action": f"Signal-triggered outreach via {channel}", "template": f"Hey {{name}}, saw {{signal_angle}}. We built a revenue system for {offer_name}. Want the breakdown?", "channel": channel},
            {"day": 4, "action": "Follow up with social proof", "template": f"Hey {{name}}, we've helped {{similar_count}} similar businesses with {offer_name}. Quick case study available.", "channel": channel},
            {"day": 8, "action": "Final touch", "template": f"Last note on the {offer_name} system. Happy to share results from similar {{segment}} businesses.", "channel": channel},
        ],
        "automated_nurture": [
            {"day": 1, "action": f"Automated email sequence start", "template": f"Subject: Revenue system for {{business}}\n\nHi {{name}},\n\nWe built a revenue system for {offer_name}. Here's what's inside:\n→ 3 paid offers\n→ 25 buyer profiles\n→ Outreach campaign\n→ Payment path\n→ Delivery receipt", "channel": "email"},
            {"day": 4, "action": "Value email with offer details", "template": f"Subject: How {{segment}} businesses are using {offer_name}\n\nHi {{name}},\n\nMost {{segment}} businesses we work with see first results within 72 hours. Here's the playbook: [link]", "channel": "email"},
            {"day": 10, "action": "Soft close", "template": f"Subject: Ready when you are\n\nHi {{name}},\n\nThe {offer_name} system is ready. If now is not the right time, I'll check back next month.", "channel": "email"},
        ],
        "monitor": [
            {"day": 1, "action": "Add to watch list", "template": f"Tracking {{name}} for re-scoring opportunities.", "channel": "none"},
            {"day": 7, "action": "Re-score", "template": "Weekly re-score check.", "channel": "none"},
        ],
    }

    sequence = sequences.get(sequence_type, sequences["automated_nurture"])

    return {
        "signal_name": signal_name,
        "persona_type": persona_type,
        "offer_name": offer_name,
        "sequence_type": sequence_type,
        "steps": sequence,
        "total_steps": len(sequence),
        "channel": channel,
        "urgency": signal.get("priority", 50),
    }


# ---------------------------------------------------------
# CAMPAIGN PLAN
# ---------------------------------------------------------

def generate_campaign_plan(revenue_os_output: dict, context: dict, request_data: Optional[dict] = None) -> dict:
    rd = revenue_os_output.get("receipt", {}).get("revenue_diagnosis", {})
    biz = rd.get("business_name", request_data.get("business_name", "Unknown") if request_data else "Unknown")
    offer_name = rd.get("current_offer", "Revenue System")
    buyers = revenue_os_output.get("buyer_profiles", [])
    offers = revenue_os_output.get("forged_offers", [])
    outreach = revenue_os_output.get("outreach_campaign", {})

    scored_buyers = [score_buyer_profile(b, context) for b in buyers]

    tier1 = [b for b in scored_buyers if b["tier"] == "Tier 1"]
    tier2 = [b for b in scored_buyers if b["tier"] == "Tier 2"]
    tier3 = [b for b in scored_buyers if b["tier"] == "Tier 3"]

    signals = context.get("signals", {}).get("signals", [])
    personas = context.get("personas", {}).get("personas", [])

    campaign_id = f"CAM-{uuid.uuid4().hex[:8].upper()}"

    sequence_plan = []
    for buyer in tier1[:3]:
        persona = next((p for p in personas if p["type"] in buyer["persona_type"].lower()), {"type": "general", "best_channel": "email"})
        sig = next(iter(buyer.get("detected_signals", [])), {"signal_name": "High ICP fit", "sequence_type": "personalized", "priority": 85})
        offer = next(iter(offers), {"name": offer_name})
        seq = build_signal_to_sequence(sig, persona, offer, context)
        sequence_plan.append(seq)

    if not sequence_plan and tier2:
        for buyer in tier2[:2]:
            persona = {"type": buyer["persona_type"], "best_channel": "email"}
            sig = {"signal_name": "Signal-triggered opportunity", "sequence_type": "signal_triggered", "priority": 70}
            offer = {"name": offer_name}
            seq = build_signal_to_sequence(sig, persona, offer, context)
            sequence_plan.append(seq)

    if not sequence_plan:
        persona = {"type": "general", "best_channel": "email"}
        sig = {"signal_name": "General opportunity", "sequence_type": "automated_nurture", "priority": 50}
        offer = {"name": offer_name}
        sequence_plan.append(build_signal_to_sequence(sig, persona, offer, context))

    campaign = {
        "id": campaign_id,
        "business_name": biz,
        "offer_name": offer_name,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "status": "draft",
        "buyer_breakdown": {
            "tier_1_count": len(tier1),
            "tier_2_count": len(tier2),
            "tier_3_count": len(tier3),
            "total_scored": len(scored_buyers),
        },
        "top_tier_buyers": scored_buyers[:5],
        "sequence_plan": sequence_plan,
        "recommended_channel": tier1[0]["best_channel"] if tier1 else "email",
        "total_sequence_steps": sum(len(s["steps"]) for s in sequence_plan),
    }

    campaigns = _load_list("campaigns")
    campaigns.append(campaign)
    _save_list("campaigns", campaigns)

    return campaign


# ---------------------------------------------------------
# WEEKLY GTM UPDATE
# ---------------------------------------------------------

def generate_weekly_gtm_update(context: dict, recent_commands: list, recent_leads: list) -> dict:
    icp = context.get("icp", {})
    segments = icp.get("icp_segments", [])

    total_commands = len(recent_commands)
    total_leads = len(recent_leads)
    paid_leads = sum(1 for l in recent_leads if l.get("status") == "paid")
    pipeline_value = sum(l.get("estimated_value", 0) or 0 for l in recent_leads)
    paid_value = sum(l.get("actual_value", 0) or 0 for l in recent_leads)

    top_segment = max(segments, key=lambda s: s.get("fit_score", 0)) if segments else {}
    commands_this_week = recent_commands[-10:] if len(recent_commands) > 10 else recent_commands

    update_id = f"WEEKLY-{uuid.uuid4().hex[:8].upper()}"

    update = {
        "id": update_id,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "period": "This week",
        "metrics": {
            "commands_run": total_commands,
            "leads_created": total_leads,
            "paid_leads": paid_leads,
            "pipeline_value": pipeline_value,
            "actual_revenue": paid_value,
        },
        "top_icp_segment": top_segment.get("segment", "General"),
        "top_icp_score": top_segment.get("fit_score", 0),
        "recommended_focus": f"Focus on {top_segment.get('segment', 'top')} segment — highest ICP fit",
        "recommended_action_items": [
            f"Run {max(5, 10 - total_commands)} more revenue commands this week",
            f"Target {max(10, 20 - total_leads)} new leads in the {top_segment.get('segment', 'top')} segment",
            "Review and re-score existing leads",
            "Send weekly outreach to monitor-tier leads",
            "Generate delivery receipts for paid leads",
        ],
        "commands_this_week": [{"id": c.get("id"), "business": c.get("business_name"), "created_at": c.get("created_at")} for c in commands_this_week],
        "next_update_cadence": "Every Monday",
    }

    updates = _load_list("weekly_updates")
    updates.append(update)
    _save_list("weekly_updates", updates)

    return update


# ---------------------------------------------------------
# ATTACH TO REVENUE OS
# ---------------------------------------------------------

def attach_gtm_to_revenue_os(revenue_os_output: dict, request_data: dict, context: dict) -> dict:
    gtm_signals = detect_signals(request_data, context)
    scored_buyers = [score_buyer_profile(b, context) for b in revenue_os_output.get("buyer_profiles", [])]
    campaign_plan = generate_campaign_plan(revenue_os_output, context, request_data)

    sequence_plan = campaign_plan.get("sequence_plan", [])
    sequence_summary = []
    for seq in sequence_plan:
        for step in seq.get("steps", []):
            sequence_summary.append({
                "day": step.get("day"),
                "action": step.get("action"),
                "channel": step.get("channel"),
            })

    gtm_layer = {
        "gtm_signals": gtm_signals,
        "icp_scores": {
            "average_score": round(sum(b.get("total_score", 0) for b in scored_buyers) / len(scored_buyers), 1) if scored_buyers else 0,
            "tier_1_count": len([b for b in scored_buyers if b["tier"] == "Tier 1"]),
            "tier_2_count": len([b for b in scored_buyers if b["tier"] == "Tier 2"]),
            "tier_3_count": len([b for b in scored_buyers if b["tier"] == "Tier 3"]),
            "monitor_count": len([b for b in scored_buyers if b["tier"] == "Monitor"]),
            "excluded_count": len([b for b in scored_buyers if b["tier"] == "Exclude"]),
        },
        "buyer_tiers": [{"persona_type": b["persona_type"], "segment": b["segment"], "total_score": b["total_score"], "tier": b["tier"], "best_channel": b["best_channel"], "recommended_sequence_type": b["recommended_sequence_type"]} for b in scored_buyers[:5]],
        "detected_signals": gtm_signals.get("detected_signals", []),
        "recommended_campaign": campaign_plan.get("id"),
        "campaign_summary": {
            "total_sequences": len(sequence_plan),
            "total_steps": campaign_plan.get("total_sequence_steps", 0),
            "top_tier_buyers": campaign_plan.get("top_tier_buyers", []),
            "recommended_channel": campaign_plan.get("recommended_channel", "email"),
        },
        "sequence_plan": sequence_summary,
        "gtm_next_actions": [
            f"Target Tier 1 buyers first ({campaign_plan.get('buyer_breakdown', {}).get('tier_1_count', 0)} identified)",
            f"Run {gtm_signals.get('signal_count', 0)} detected signal(s) through personalized sequences",
            f"Best channel: {gtm_signals.get('best_channel', 'mixed')}",
            "Review campaign plan for full sequence details",
            "Track lead statuses in Pipeline Composer and update scores weekly",
        ],
    }

    revenue_os_output["gtm_layer"] = gtm_layer
    return revenue_os_output
