'use client';

import { useEffect, useMemo, useState } from 'react';

type Campaign = { id:string; name:string; status:string; channels:string[]; max_total_actions:number; authorization?:{max_actions:number;expires_at:string}; counters:Record<string,number> };
type Job = { id:string; campaign_id:string; channel:string; destination:string; status:string; provider_message?:string; outcome?:string };
type Summary = { provider_status:Record<string,unknown>; metrics:Record<string,number>; campaigns:Campaign[]; jobs:Job[]; receipts:Array<{id:string;event:string;created_at:string;receipt_sha256:string}> };

const POST = `Most businesses do not need a giant AI transformation.\n\nThey need one broken workflow fixed.\n\nEmpire-1's free AI Workflow Leak Snapshot shows the likely leak, first credible automation opportunity, human-control boundary, and proof the finished system should leave.\n\nRun it: https://empire1.cloud/services/scan`;
const EMAIL = `I noticed your operation may still have a workflow depending on inboxes, spreadsheets, and memory. Empire-1 built a free Workflow Leak Snapshot that maps one broken workflow and the smallest credible fix.\n\nRun it here: https://empire1.cloud/services/scan`;
const DM = `Hey — I built a free Workflow Leak Snapshot for businesses losing time, leads, money, or control through one broken workflow. Worth sending you the link?`;
const input = 'rounded-xl border border-white/10 bg-black px-3 py-2.5 text-white outline-none focus:border-amber-300/60';
const card = 'rounded-2xl border border-white/10 bg-zinc-950 p-5';
const lines = (value:string) => Array.from(new Set(value.split(/\r?\n|,/).map(v=>v.trim()).filter(Boolean)));

export default function ControlledPublisher(){
  const [key,setKey]=useState(''); const [data,setData]=useState<Summary|null>(null); const [selectedId,setSelectedId]=useState('');
  const [busy,setBusy]=useState(''); const [message,setMessage]=useState(''); const [error,setError]=useState('');
  const [approver,setApprover]=useState('Manda Mora'); const [emails,setEmails]=useState(''); const [dms,setDms]=useState('');
  const [post,setPost]=useState(POST); const [emailBody,setEmailBody]=useState(EMAIL); const [dmBody,setDmBody]=useState(DM);
  useEffect(()=>setKey(sessionStorage.getItem('empire-publisher-key')||''),[]);
  const campaigns=data?.campaigns||[]; const selected=useMemo(()=>campaigns.find(c=>c.id===selectedId)||campaigns[0]||null,[campaigns,selectedId]);
  const jobs=(data?.jobs||[]).filter(j=>!selected||j.campaign_id===selected.id);

  async function api(path:string,method:'GET'|'POST'='GET',body?:unknown){
    const res=await fetch(`/api/gtm/publisher${path}`,{method,headers:{'Content-Type':'application/json','x-empire-publisher-key':key},body:method==='POST'?JSON.stringify(body||{}):undefined,cache:'no-store'});
    const out=await res.json(); if(!res.ok||!out.success) throw new Error(out.detail||'Publisher request failed.'); return out;
  }
  async function run(label:string,fn:()=>Promise<string>){setBusy(label);setError('');setMessage('');try{setMessage(await fn());}catch(e){setError(e instanceof Error?e.message:'Action failed.');}finally{setBusy('');}}
  async function refresh(){const out=await api('/summary');setData(out);if(!selectedId&&out.campaigns?.[0]?.id)setSelectedId(out.campaigns[0].id);}
  async function unlock(){await run('unlock',async()=>{sessionStorage.setItem('empire-publisher-key',key);await refresh();return 'Founder control unlocked for this browser session.';});}
  async function create(){await run('create',async()=>{const out=await api('/campaigns','POST',{name:'Workflow Leak Snapshot — 7 Day Launch',offer_name:'Free AI Workflow Leak Snapshot',audience:'Founder-led businesses with one visible manual workflow',objective:'Drive qualified scan completions and human-reviewed conversations',primary_url:'https://empire1.cloud/services/scan',channels:['linkedin','email','dm'],daily_action_limit:20,max_total_actions:150,requires_human_reply:true});setSelectedId(out.campaign.id);await refresh();return `${out.campaign.id} created.`;});}
  async function gate(action:'approve'|'authorize'|'revoke'){if(!selected)return;await run(action,async()=>{const body=action==='approve'?{approved_by:approver,confirm_claims_verified:true,confirm_scope_understood:true}:action==='authorize'?{authorized_by:approver,channels:selected.channels,max_actions:selected.max_total_actions,expires_in_hours:168,confirm_external_actions:true,confirm_no_mass_spam:true}:{revoked_by:approver,reason:'Founder revoked campaign authorization.'};await api(`/campaigns/${selected.id}/${action}`,'POST',body);await refresh();return `${action.toUpperCase()} recorded with receipt.`;});}
  async function queue(){if(!selected)return;const batch:Array<Record<string,unknown>>=[];if(post.trim())batch.push({channel:'linkedin',destination:'founder-linkedin-profile',content:post});for(const e of lines(emails))batch.push({channel:'email',destination:e,subject:'Free workflow leak snapshot for one broken process',content:emailBody});for(const d of lines(dms))batch.push({channel:'dm',destination:d,content:dmBody});if(!batch.length){setError('Add at least one explicit job.');return;}await run('queue',async()=>{const out=await api(`/campaigns/${selected.id}/queue`,'POST',{jobs:batch});await refresh();return `${out.jobs.length} queued; ${out.skipped_duplicates} duplicates skipped.`;});}
  async function dispatch(path:string,label:string){await run(label,async()=>{const out=await api(path,'POST',{confirmed_by:approver,confirm_external_action:true,max_jobs:10});await refresh();return out.results?`${out.attempted} attempted.`:`${out.job.status}: ${out.job.provider_message||'provider accepted'}`;});}
  async function outcome(job:Job,value:string){await run(`${job.id}-${value}`,async()=>{await api(`/jobs/${job.id}/outcome`,'POST',{outcome:value,recorded_by:approver});await refresh();return `${value} recorded.`;});}
  const enabled=Boolean(key)&&!busy;

  return <div className="min-h-screen bg-black text-white"><div className="mx-auto max-w-7xl space-y-6 px-5 py-8 sm:px-8">
    <section className="rounded-3xl border border-amber-300/20 bg-gradient-to-br from-amber-300/10 via-zinc-950 to-black p-7"><p className="text-xs font-black uppercase tracking-[.25em] text-amber-300">Empire-1 Controlled Publisher</p><h1 className="mt-4 text-3xl font-black sm:text-5xl">Draft → approve → authorize → publish → receipt.</h1><p className="mt-4 max-w-4xl text-sm leading-7 text-zinc-300">The Cofounder now has a scoped launch queue, batch dispatch, provider truth, daily limits, revocation, outcomes, and an evidence trail.</p></section>
    <section className={`${card} grid gap-3 lg:grid-cols-[1fr_auto]`}><label className="grid gap-2 text-sm">Founder operator key<input type="password" value={key} onChange={(e:{target:{value:string}})=>setKey(e.target.value)} className={input} placeholder="EMPIRE_PUBLISHER_KEY"/><span className="text-xs text-zinc-600">Stored only in sessionStorage.</span></label><div className="flex items-end gap-2"><button onClick={unlock} disabled={!key||!!busy} className="rounded-xl bg-white px-4 py-2.5 text-sm font-black text-black disabled:opacity-30">Unlock</button><button onClick={()=>refresh()} disabled={!enabled} className="rounded-xl border border-white/10 px-4 py-2.5 text-sm font-bold disabled:opacity-30">Refresh</button></div></section>
    {message&&<p className="rounded-xl border border-emerald-400/20 bg-emerald-500/10 p-3 text-sm text-emerald-200">{message}</p>}{error&&<p className="rounded-xl border border-red-400/20 bg-red-500/10 p-3 text-sm text-red-200">{error}</p>}
    {data&&<><section className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{Object.entries(data.metrics).map(([k,v])=><Metric key={k} label={k} value={v}/>)}</section><section className={card}><h2 className="text-sm font-black uppercase tracking-[.18em] text-zinc-400">Provider truth</h2><pre className="mt-3 overflow-auto whitespace-pre-wrap text-xs text-zinc-400">{JSON.stringify(data.provider_status,null,2)}</pre></section></>}
    <section className="grid gap-6 xl:grid-cols-[.75fr_1.25fr]"><div className="space-y-6"><section className={card}><h2 className="font-black">Campaign control</h2><button onClick={create} disabled={!enabled} className="mt-4 w-full rounded-xl bg-white px-4 py-3 text-sm font-black text-black disabled:opacity-30">Create 7-Day Scan Campaign</button><div className="mt-4 space-y-2">{campaigns.map(c=><button key={c.id} onClick={()=>setSelectedId(c.id)} className={`w-full rounded-xl border p-3 text-left ${selected?.id===c.id?'border-amber-300/50 bg-amber-300/10':'border-white/10 bg-black'}`}><span className="text-xs font-black text-amber-200">{c.status}</span><p className="mt-1 text-sm font-semibold">{c.name}</p><p className="text-[10px] text-zinc-600">{c.id}</p></button>)}</div></section></div>
      <div className="space-y-6"><section className={card}><h2 className="font-black">Founder gate</h2>{selected?<><p className="mt-3 text-sm text-zinc-400">{selected.status} · {selected.counters.dispatched||0}/{selected.authorization?.max_actions||selected.max_total_actions} dispatched</p><label className="mt-3 grid gap-2 text-sm">Approver<input value={approver} onChange={(e:{target:{value:string}})=>setApprover(e.target.value)} className={input}/></label><div className="mt-3 flex flex-wrap gap-2"><Button text="Approve" onClick={()=>gate('approve')} disabled={!enabled||selected.status!=='DRAFTED'}/><Button text="Authorize 7 Days" onClick={()=>gate('authorize')} disabled={!enabled||selected.status!=='FOUNDER_APPROVED'}/><Button text="Revoke" onClick={()=>gate('revoke')} disabled={!enabled||!['AUTHORIZED','ACTIVE'].includes(selected.status)}/></div></>:<p className="mt-3 text-sm text-zinc-600">Create a campaign first.</p>}</section>
      <section className={card}><h2 className="font-black">Queue launch pack</h2><Area label="LinkedIn post" value={post} set={setPost}/><Area label="Email targets — one per line" value={emails} set={setEmails}/><Area label="Email body" value={emailBody} set={setEmailBody}/><Area label="DM targets — one per line" value={dms} set={setDms}/><Area label="DM body" value={dmBody} set={setDmBody}/><button onClick={queue} disabled={!enabled||!selected||!['AUTHORIZED','ACTIVE'].includes(selected.status)} className="mt-3 w-full rounded-xl bg-white px-4 py-3 text-sm font-black text-black disabled:opacity-30">Queue Explicit Jobs</button></section></div></section>
    <section className={card}><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-black">Dispatch + outcomes</h2><p className="text-xs text-zinc-600">Provider success is required for DISPATCHED.</p></div><button onClick={()=>selected&&dispatch(`/campaigns/${selected.id}/dispatch-batch`,'batch')} disabled={!enabled||!selected||!jobs.some(j=>['QUEUED','BLOCKED','FAILED'].includes(j.status))} className="rounded-xl bg-amber-300 px-4 py-2 text-sm font-black text-black disabled:opacity-30">Dispatch Next 10</button></div><div className="mt-4 space-y-2">{jobs.map(j=><div key={j.id} className="grid gap-2 rounded-xl border border-white/10 bg-black p-3 lg:grid-cols-[100px_90px_1fr_auto] lg:items-center"><b className="text-xs">{j.status}{j.outcome?` / ${j.outcome}`:''}</b><span className="text-xs text-amber-200">{j.channel}</span><div><p className="text-sm">{j.destination}</p><p className="text-xs text-zinc-600">{j.provider_message||j.id}</p></div><div className="flex flex-wrap gap-1"><Button text="Dispatch" onClick={()=>dispatch(`/jobs/${j.id}/dispatch`,j.id)} disabled={!enabled||!['QUEUED','BLOCKED','FAILED'].includes(j.status)}/>{['REPLIED','CONVERTED','VERIFIED'].map(v=><Button key={v} text={v} onClick={()=>outcome(j,v)} disabled={!enabled||!['DISPATCHED','MANUAL_READY'].includes(j.status)}/>)}</div></div>)}</div></section>
    <section className={card}><h2 className="font-black">Receipt chain</h2><div className="mt-3 grid gap-2 md:grid-cols-2">{(data?.receipts||[]).slice(0,10).map(r=><div key={r.id} className="rounded-xl border border-white/10 bg-black p-3"><b className="text-xs text-amber-200">{r.event}</b><p className="mt-2 break-all font-mono text-[10px] text-zinc-600">{r.receipt_sha256}</p></div>)}</div></section>
  </div></div>;
}

function Metric({label,value}:{label:string;value:number}){return <div className="rounded-xl border border-white/10 bg-zinc-950 p-4"><p className="text-[10px] uppercase text-zinc-600">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></div>}
function Button({text,onClick,disabled}:{text:string;onClick:()=>void;disabled:boolean;key?:string}){return <button onClick={onClick} disabled={disabled} className="rounded-lg border border-white/10 px-3 py-2 text-xs font-bold disabled:opacity-30">{text}</button>}
function Area({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label className="mt-3 grid gap-1 text-sm text-zinc-300">{label}<textarea value={value} onChange={(e:{target:{value:string}})=>set(e.target.value)} rows={4} className={input}/></label>}
