'use client';

import { useEffect, useMemo, useState } from 'react';

type Platform = 'meta' | 'google_ads' | 'x_ads';
type Campaign = {
  id:string; name:string; status:string; platforms:Platform[]; landing_url:string;
  authorization?:{currency:string;daily_cap_cents:number;total_cap_cents:number;expires_at:string;revision:number};
  metrics:{spend_cents:number;impressions:number;clicks:number;conversions:number;conversion_value_cents:number;synced_at?:string};
  provider_bindings:Record<string,{campaign_id?:string;status?:string;last_message?:string}>;
  pause_reason?:string;
};
type Summary = {
  provider_status:Record<string,unknown>;
  metrics:Record<string,number>;
  campaigns:Campaign[];
  receipts:Array<{id:string;event:string;created_at:string;receipt_sha256:string}>;
};

const field='rounded-xl border border-white/10 bg-black px-3 py-2.5 text-white outline-none focus:border-amber-300/60';
const card='rounded-2xl border border-white/10 bg-zinc-950 p-5';
const money=(cents:number,currency='USD')=>new Intl.NumberFormat('en-US',{style:'currency',currency}).format((cents||0)/100);

export default function PaidMediaControlPlane(){
  const [key,setKey]=useState(''); const [data,setData]=useState<Summary|null>(null); const [selectedId,setSelectedId]=useState('');
  const [busy,setBusy]=useState(''); const [message,setMessage]=useState(''); const [error,setError]=useState(''); const [founder,setFounder]=useState('Manda Mora');
  const [platforms,setPlatforms]=useState<Platform[]>(['meta','google_ads','x_ads']);
  const [headline,setHeadline]=useState('Find the workflow costing your business time, leads, money, or control.');
  const [copy,setCopy]=useState("Empire-1's free Workflow Leak Snapshot identifies one broken workflow, the first credible automation opportunity, the human-control boundary, and the evidence the finished system should leave.");
  const [assets,setAssets]=useState(''); const [daily,setDaily]=useState('20'); const [total,setTotal]=useState('140'); const [noConversion,setNoConversion]=useState('30'); const [maxCpa,setMaxCpa]=useState('35');
  const [amendReason,setAmendReason]=useState('Adjust paid-media budget after reviewing performance.');
  const [metaAccount,setMetaAccount]=useState(''); const [googleAccount,setGoogleAccount]=useState(''); const [xAccount,setXAccount]=useState('');
  useEffect(()=>setKey(sessionStorage.getItem('empire-paid-media-key')||sessionStorage.getItem('empire-publisher-key')||''),[]);
  const campaigns=data?.campaigns||[]; const selected=useMemo(()=>campaigns.find(c=>c.id===selectedId)||campaigns[0]||null,[campaigns,selectedId]);
  async function api(path:string,body?:unknown){const res=await fetch(`/api/gtm/paid-media${path}`,{method:body?'POST':'GET',headers:{'Content-Type':'application/json','x-empire-paid-media-key':key},body:body?JSON.stringify(body):undefined,cache:'no-store'});const out=await res.json();if(!res.ok||!out.success)throw new Error(out.detail||'Paid media request failed.');return out;}
  async function run(label:string,work:()=>Promise<string>){setBusy(label);setMessage('');setError('');try{setMessage(await work());}catch(e){setError(e instanceof Error?e.message:'Action failed.');}finally{setBusy('');}}
  async function refresh(){const out=await api('/summary');setData(out);if(!selectedId&&out.campaigns?.[0]?.id)setSelectedId(out.campaigns[0].id);}
  async function unlock(){await run('unlock',async()=>{sessionStorage.setItem('empire-paid-media-key',key);await refresh();return 'Paid-media founder control unlocked for this browser session.';});}
  const toggle=(platform:Platform)=>setPlatforms(current=>current.includes(platform)?current.filter(item=>item!==platform):[...current,platform]);
  async function create(){await run('create',async()=>{const out=await api('/campaigns',{name:'Workflow Leak Snapshot — Paid Funnel Test',offer_name:'Free AI Workflow Leak Snapshot',objective:'Generate completed scans and qualified founder-review requests',audience:'Founder-led businesses with one visible broken workflow in Southern California',landing_url:'https://empire1.cloud/services/scan',platforms});setSelectedId(out.campaign.id);await refresh();return `${out.campaign.id} created without spend authority.`;});}
  async function approve(){if(!selected)return;await run('approve',async()=>{await api(`/campaigns/${selected.id}/approve-creative`,{approved_by:founder,headline,primary_text:copy,description:'One workflow. One practical first move. Human control stays visible.',call_to_action:'LEARN_MORE',asset_urls:assets.split(/\r?\n|,/).map(v=>v.trim()).filter(Boolean),claims:['Preliminary browser-generated snapshot','No guaranteed savings or outcomes'],confirm_claims_verified:true,confirm_landing_page_verified:true,confirm_creative_rights:true});await refresh();return 'Creative and claims approved with a receipt.';});}
  async function authorize(){if(!selected)return;const expires=new Date(Date.now()+7*24*60*60*1000).toISOString();await run('authorize',async()=>{await api(`/campaigns/${selected.id}/authorize-budget`,{authorized_by:founder,currency:'USD',daily_cap_cents:Math.round(Number(daily)*100),total_cap_cents:Math.round(Number(total)*100),start_at:new Date().toISOString(),expires_at:expires,target_geography:['Southern California'],platform_accounts:{meta:metaAccount,google_ads:googleAccount,x_ads:xAccount},max_cost_per_conversion_cents:Math.round(Number(maxCpa)*100),no_conversion_pause_cents:Math.round(Number(noConversion)*100),confirm_direct_billing:true,confirm_account_authority:true,confirm_budget_caps:true});await refresh();return `Seven-day budget authorized: ${money(Math.round(Number(total)*100))} total cap.`;});}
  async function amend(){if(!selected)return;const expires=new Date(Date.now()+7*24*60*60*1000).toISOString();await run('amend',async()=>{await api(`/campaigns/${selected.id}/amend-budget`,{authorized_by:founder,currency:'USD',daily_cap_cents:Math.round(Number(daily)*100),total_cap_cents:Math.round(Number(total)*100),start_at:new Date().toISOString(),expires_at:expires,target_geography:['Southern California'],platform_accounts:{meta:metaAccount,google_ads:googleAccount,x_ads:xAccount},max_cost_per_conversion_cents:Math.round(Number(maxCpa)*100),no_conversion_pause_cents:Math.round(Number(noConversion)*100),confirm_direct_billing:true,confirm_account_authority:true,confirm_budget_caps:true,confirm_budget_increase:true,reason:amendReason});await refresh();return 'Budget amendment authorized with a new revision receipt.';});}
  async function syncAll(){await run('sync-all',async()=>{const out=await api('/sync-all',{synced_by:founder});await refresh();return `${out.attempted} live campaigns synced.`;});}
  async function action(name:'launch'|'pause'|'sync'|'revoke-providers'){if(!selected)return;await run(name,async()=>{const bodies={launch:{launched_by:founder,confirm_external_spend:true},pause:{paused_by:founder,reason:'Founder paused paid media.'},sync:{synced_by:founder},'revoke-providers':{revoked_by:founder,reason:'Founder revoked provider execution.'}};await api(`/campaigns/${selected.id}/${name}`,bodies[name]);await refresh();return `${name.toUpperCase()} completed or truthfully recorded as blocked.`;});}
  const enabled=Boolean(key)&&!busy;
  return <div className="min-h-screen bg-black text-white"><div className="mx-auto max-w-7xl space-y-6 px-5 py-8 sm:px-8">
    <section className="rounded-3xl border border-amber-300/20 bg-gradient-to-br from-amber-300/10 via-zinc-950 to-black p-7"><p className="text-xs font-black uppercase tracking-[.25em] text-amber-300">Empire-1 Paid Media Governance</p><h1 className="mt-4 text-3xl font-black sm:text-5xl">Approve the creative. Authorize the money. Control the funnel.</h1><p className="mt-4 max-w-4xl text-sm leading-7 text-zinc-300">Meta, Google Ads, and X Ads operate only inside a founder-approved ad account, geography, date window, daily cap, total cap, and automatic pause rule. Budget increases require a new authorization.</p></section>
    <section className={`${card} grid gap-3 lg:grid-cols-[1fr_auto]`}><label className="grid gap-2 text-sm">Founder paid-media key<input type="password" value={key} onChange={(e:{target:{value:string}})=>setKey(e.target.value)} className={field} placeholder="EMPIRE_PAID_MEDIA_KEY"/><span className="text-xs text-zinc-600">Falls back to EMPIRE_PUBLISHER_KEY and stays in sessionStorage.</span></label><div className="flex items-end gap-2"><button onClick={unlock} disabled={!key||!!busy} className="rounded-xl bg-white px-4 py-2.5 text-sm font-black text-black disabled:opacity-30">Unlock</button><button onClick={refresh} disabled={!enabled} className="rounded-xl border border-white/10 px-4 py-2.5 text-sm font-bold disabled:opacity-30">Refresh</button></div></section>
    {message&&<p className="rounded-xl border border-emerald-400/20 bg-emerald-500/10 p-3 text-sm text-emerald-200">{message}</p>}{error&&<p className="rounded-xl border border-red-400/20 bg-red-500/10 p-3 text-sm text-red-200">{error}</p>}
    {data&&<><section className="grid gap-3 sm:grid-cols-3 lg:grid-cols-7">{Object.entries(data.metrics).map(([label,value])=><Metric key={label} label={label} value={label.includes('cents')?money(value):String(value)}/>)}</section><section className={card}><h2 className="text-sm font-black uppercase tracking-[.18em] text-zinc-400">Provider truth</h2><pre className="mt-3 overflow-auto whitespace-pre-wrap text-xs text-zinc-400">{JSON.stringify(data.provider_status,null,2)}</pre></section></>}
    <section className="grid gap-6 xl:grid-cols-[.72fr_1.28fr]"><div className="space-y-6"><section className={card}><h2 className="font-black">Campaigns</h2><div className="mt-4 flex flex-wrap gap-2">{(['meta','google_ads','x_ads'] as Platform[]).map(p=><button key={p} onClick={()=>toggle(p)} className={`rounded-full border px-3 py-1.5 text-xs font-bold ${platforms.includes(p)?'border-amber-300/60 bg-amber-300/10 text-amber-100':'border-white/10 text-zinc-600'}`}>{p}</button>)}</div><button onClick={create} disabled={!enabled||!platforms.length} className="mt-4 w-full rounded-xl bg-white px-4 py-3 text-sm font-black text-black disabled:opacity-30">Create Paid Funnel Campaign</button><div className="mt-4 space-y-2">{campaigns.map(c=><button key={c.id} onClick={()=>setSelectedId(c.id)} className={`w-full rounded-xl border p-3 text-left ${selected?.id===c.id?'border-amber-300/50 bg-amber-300/10':'border-white/10 bg-black'}`}><span className="text-xs font-black text-amber-200">{c.status}</span><p className="mt-1 text-sm font-semibold">{c.name}</p><p className="text-[10px] text-zinc-600">{c.id} · {c.platforms.join(', ')}</p></button>)}</div></section>
      {selected&&<section className={card}><h2 className="font-black">Live economics</h2><div className="mt-3 grid grid-cols-2 gap-2 text-sm"><Mini label="Spend" value={money(selected.metrics.spend_cents,selected.authorization?.currency||'USD')}/><Mini label="Clicks" value={String(selected.metrics.clicks)}/><Mini label="Conversions" value={String(selected.metrics.conversions)}/><Mini label="Value" value={money(selected.metrics.conversion_value_cents,selected.authorization?.currency||'USD')}/></div>{selected.pause_reason&&<p className="mt-3 rounded-lg border border-red-400/20 bg-red-500/10 p-2 text-xs text-red-200">{selected.pause_reason}</p>}</section>}</div>
      <div className="space-y-6"><section className={card}><h2 className="font-black">1. Creative approval</h2><Area label="Headline" value={headline} set={setHeadline} rows={2}/><Area label="Primary text" value={copy} set={setCopy}/><Area label="Approved image/video URLs — one per line" value={assets} set={setAssets}/><button onClick={approve} disabled={!enabled||!selected||!['DRAFTED','CREATIVE_APPROVED'].includes(selected.status)} className="mt-3 w-full rounded-xl border border-white/10 px-4 py-3 text-sm font-black disabled:opacity-30">Approve Creative + Claims</button></section>
      <section className={card}><h2 className="font-black">2. Budget authorization</h2><div className="mt-3 grid gap-3 sm:grid-cols-2"><MoneyField label="Daily cap" value={daily} set={setDaily}/><MoneyField label="Total 7-day cap" value={total} set={setTotal}/><MoneyField label="Pause after spend with zero conversions" value={noConversion} set={setNoConversion}/><MoneyField label="Maximum cost per conversion" value={maxCpa} set={setMaxCpa}/></div><Text label="Meta ad account ID" value={metaAccount} set={setMetaAccount}/><Text label="Google Ads customer ID" value={googleAccount} set={setGoogleAccount}/><Text label="X Ads account ID" value={xAccount} set={setXAccount}/><button onClick={authorize} disabled={!enabled||!selected||selected.status!=='CREATIVE_APPROVED'} className="mt-3 w-full rounded-xl bg-white px-4 py-3 text-sm font-black text-black disabled:opacity-30">Authorize 7-Day Spend Boundary</button><Area label="Budget amendment reason" value={amendReason} set={setAmendReason} rows={2}/><button onClick={amend} disabled={!enabled||!selected||!['PAUSED','AUTO_PAUSED','BUDGET_AUTHORIZED'].includes(selected.status)} className="mt-3 w-full rounded-xl border border-amber-300/30 px-4 py-3 text-sm font-black text-amber-100 disabled:opacity-30">Authorize Budget Amendment</button></section>
      <section className={card}><h2 className="font-black">3. Execute + stop</h2><label className="mt-3 grid gap-2 text-sm">Founder / client approver<input value={founder} onChange={(e:{target:{value:string}})=>setFounder(e.target.value)} className={field}/></label><div className="mt-3 flex flex-wrap gap-2"><Button text="Sync All Live" onClick={syncAll} disabled={!enabled}/><Button text="Launch Ads" onClick={()=>action('launch')} disabled={!enabled||!selected||selected.status!=='BUDGET_AUTHORIZED'}/><Button text="Sync Spend" onClick={()=>action('sync')} disabled={!enabled||!selected||!['LIVE','PAUSED','AUTO_PAUSED','PAUSE_REQUESTED','BLOCKED'].includes(selected.status)}/><Button text="Pause" onClick={()=>action('pause')} disabled={!enabled||!selected||!['LIVE','PAUSE_REQUESTED','BLOCKED'].includes(selected.status)}/><Button text="Revoke Providers" onClick={()=>action('revoke-providers')} disabled={!enabled||!selected||!['LIVE','PAUSED','AUTO_PAUSED','PAUSE_REQUESTED','BLOCKED'].includes(selected.status)}/></div></section></div></section>
    {selected&&<section className={card}><h2 className="font-black">Provider bindings</h2><pre className="mt-3 overflow-auto whitespace-pre-wrap text-xs text-zinc-400">{JSON.stringify(selected.provider_bindings,null,2)}</pre></section>}
    <section className={card}><h2 className="font-black">Paid-media receipt chain</h2><div className="mt-3 grid gap-2 md:grid-cols-2">{(data?.receipts||[]).slice(0,14).map(r=><div key={r.id} className="rounded-xl border border-white/10 bg-black p-3"><b className="text-xs text-amber-200">{r.event}</b><p className="mt-2 break-all font-mono text-[10px] text-zinc-600">{r.receipt_sha256}</p></div>)}</div></section>
  </div></div>;
}
function Metric({label,value}:{label:string;value:string;key?:string}){return <div className="rounded-xl border border-white/10 bg-zinc-950 p-4"><p className="text-[10px] uppercase text-zinc-600">{label}</p><p className="mt-1 text-xl font-black">{value}</p></div>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-lg border border-white/10 bg-black p-3"><p className="text-[10px] uppercase text-zinc-600">{label}</p><b>{value}</b></div>}
function Button({text,onClick,disabled}:{text:string;onClick:()=>void;disabled:boolean}){return <button onClick={onClick} disabled={disabled} className="rounded-lg border border-white/10 px-3 py-2 text-xs font-bold disabled:opacity-30">{text}</button>}
function Area({label,value,set,rows=4}:{label:string;value:string;set:(v:string)=>void;rows?:number}){return <label className="mt-3 grid gap-1 text-sm text-zinc-300">{label}<textarea value={value} onChange={(e:{target:{value:string}})=>set(e.target.value)} rows={rows} className={field}/></label>}
function Text({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label className="mt-3 grid gap-1 text-sm text-zinc-300">{label}<input value={value} onChange={(e:{target:{value:string}})=>set(e.target.value)} className={field}/></label>}
function MoneyField({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label className="grid gap-1 text-sm text-zinc-300">{label}<div className="flex items-center rounded-xl border border-white/10 bg-black"><span className="px-3 text-zinc-600">$</span><input type="number" min="1" step="1" value={value} onChange={(e:{target:{value:string}})=>set(e.target.value)} className="w-full bg-transparent px-1 py-2.5 text-white outline-none"/></div></label>}
